version: 2

jobs:
  lint:
    docker:
    - image: node:latest
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: yarn install
    - run:
        name: Run Lint
        command: npm run lint
  test:
    docker:
    - image: node:10.6.0
    steps:
    - checkout
    - run: npm install -g react-scripts
    - run:
        name: Install Dependencies
        command: yarn install
    - run:
        name: Run tests
        command: npm test

  deploy:
    machine:
      enabled: true
    steps:
    - run:
        name: Deploy to dirdapi.chaz.pro
        command: |
          ssh $SSH_USER@$SSH_HOST "~/deploy/squawkfront.sh"


workflows:
  version: 2
  build_and_test:
    jobs:
    - lint
    - test
    - deploy:
        requires:
        - test
        filters:
          branches:
            only: master

