version: 2

jobs:
  test:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd api && GO111MODULE=on go mod vendor
      - run:
          name: Run tests
          command: cd api/pkg && go test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test